[[users]]
# 在下方双引号中填入登录的手机号
phoneNumber = ""
# 在下方双引号中填入登陆密码
password = ""
# 在下方双引号中填入从VMOS获取的IMEI
deviceID = ""
# 在下方双引号中填入用于通知的邮箱
email = ""
# 在下方双引号中填入邮箱授权码
emailPassword = ""
# 在下方双引号中填入server酱token
serverJ = ""
# 在下方双引号中填入push+ token
pushPlus = ""
# 是否进行健康打卡? 是: true, 否:false
healthyCheck = true
# 是否进行校内打卡? 是: true, 否:false
inSchoolCheck = true

#如果需要进行多人打卡按照如下格式即可

# [[users]]
# phoneNumber = ""
# password = ""
# deviceID = ""
# email = ""
# emailPassword = ""
# serverJ = ""
# pushPlus = ""
# healthyCheck = true
# inSchoolCheck = true